# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'academic plan',
            },
        ),
        migrations.CreateModel(
            name='Academic_step',
            fields=[
                ('academic_step_kod', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('academic_step_name', models.CharField(max_length=50)),
                ('academic_step_costlec', models.IntegerField(default=0)),
                ('academic_step_costlab', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'academic step',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_kod', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.IntegerField(default=1)),
                ('salary_scrip', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_kod', models.IntegerField(primary_key=True, serialize=False)),
                ('speciality_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'speciality',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fname', models.CharField(max_length=200)),
                ('student_lname', models.CharField(max_length=200)),
                ('student_kod', models.IntegerField(default=0)),
                ('student_kodorg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Organization')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_name', models.CharField(max_length=200)),
                ('subject_kod_pred', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('subject_lect', models.IntegerField(default=0)),
                ('subject_lab', models.IntegerField(default=0)),
                ('subject_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Speciality')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_kod', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('teacher_fname', models.CharField(max_length=200)),
                ('teacher_lname', models.CharField(max_length=200)),
                ('teacher_countlec', models.IntegerField(default=0)),
                ('teacher_countlab', models.IntegerField(default=0)),
                ('teacher_kodstep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Academic_step')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_dates', models.IntegerField(default=0)),
                ('training_cost', models.IntegerField(default=0)),
                ('training_hostel', models.BooleanField(default=True)),
                ('training_shifr', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('training_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Speciality')),
            ],
            options={
                'db_table': 'training',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_shifr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Training'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Speciality'),
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_kodv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Teacher'),
        ),
        migrations.AddField(
            model_name='academic_plan',
            name='academic_kodsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Subject'),
        ),
        migrations.AddField(
            model_name='academic_plan',
            name='academic_shifr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Training'),
        ),
        migrations.AddField(
            model_name='academic_plan',
            name='academic_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Speciality'),
        ),
        migrations.AddField(
            model_name='academic_plan',
            name='academic_teach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Teacher'),
        ),
    ]
