# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20161213_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
