# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_student_student_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_plan',
            name='academic_spec',
        ),
    ]
