# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_academic_plan_academic_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='salary_month',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_lab',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_lect',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_countlab',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_countlec',
        ),
        migrations.AddField(
            model_name='academic_plan',
            name='academic_lab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academic_plan',
            name='academic_lec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academic_plan',
            name='academic_month',
            field=models.IntegerField(default=1),
        ),
    ]
