# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20161213_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='salary_mouth',
            field=models.IntegerField(default=1),
        ),
    ]
