# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20170614_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id_algor',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
