# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_customer_customer_id_algor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alrogithm',
            name='algorithm_customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id_algor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Alrogithm'),
        ),
    ]
