# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20170614_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='alrogithm',
            name='algorithm_value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
