# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20170615_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='alrogithm',
            name='algorithm_creater',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
