# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alrogithm_algorithm_creater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_plan',
            name='academic_kodsub',
        ),
        migrations.RemoveField(
            model_name='academic_plan',
            name='academic_shifr',
        ),
        migrations.RemoveField(
            model_name='academic_plan',
            name='academic_teach',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary_kodv',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_kodorg',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_shifr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_kodstep',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_spec',
        ),
        migrations.DeleteModel(
            name='Academic_plan',
        ),
        migrations.DeleteModel(
            name='Academic_step',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
